version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - FRONTEND_URL=http://${GCP_STATIC_IP}:3000
    ports:
      - "8000:8000"
    volumes:
      - ./investigations.db:/app/investigations.db
    restart: unless-stopped

  frontend:
    image: us-central1-docker.pkg.dev/github-cicd-pipeline/hubspot-repo/frontend:latest
    environment:
      - NEXT_PUBLIC_API_URL=http://34.72.137.250:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped